version: '3.8'
x-noalbs:
  &default-noalbs-v2
  build:
      context: .
      dockerfile: ./Dockerfile.noalbs-v2-sls
  image: ${REPOSITORY_NAME}/noalbs-v2:${GLOBAL_VERSION}
x-noalbs:
  &default-noalbs-v1
  build:
      context: .
      dockerfile: ./Dockerfile.noalbs-sls
  image: ${REPOSITORY_NAME}/noalbs-v1:${GLOBAL_VERSION}
services:
  belabox-srtla-receiver:
    build:
        context: .
        dockerfile: ./Dockerfile.belabox-srtla-receiver
    image: ${REPOSITORY_NAME}/${PROJECT_NAME}-belabox-srtla-receiver:${GLOBAL_VERSION}
  noalbs-srtla:
    build:
      context: .
      dockerfile: ./Dockerfile.noalbs-srtla
    image: ${REPOSITORY_NAME}/noalbs-srtla:${GLOBAL_VERSION}
  noalbs-v1_latest:
    *default-noalbs-v1
  noalbs_latest:
    <<: *default-noalbs-v1
    image: ${REPOSITORY_NAME}/noalbs:${GLOBAL_VERSION}
  noalbs-v1_sls_latest:
    <<: *default-noalbs-v1
    image: ${REPOSITORY_NAME}/noalbs-sls:${GLOBAL_VERSION}
  noalbs-v2_latest:
    *default-noalbs-v2
  noalbs-v2_sls_latest:
    <<: *default-noalbs-v2
    image: ${REPOSITORY_NAME}/noalbs-v2-sls:${GLOBAL_VERSION}
  srtla:
    build:
      context: .
      dockerfile: ./Dockerfile.srtla
    image: ${REPOSITORY_NAME}/srtla:${GLOBAL_VERSION}